player_mappings = {
    'G.G. Jackson': 'Gregory Jackson',
    'Cam Payne': 'Cameron Payne',
    'R.J. Barrett': 'RJ Barrett',
    'Jabari Smith Jr': 'Jabari Smith Jr.',
    'Gary Trent': 'Gary Trent Jr.',
    'Matthew Hurt': 'Matt Hurt',
    'MarJon Beauchamp': 'Marjon Beauchamp',
    'Kev Durant': 'Kevin Durant',
    'Jabari Smith Jr': 'Jabari Smith Jr.',
    'Lonnie Walker': 'Lonnie Walker IV',
    'Derrick Jones': 'Derrick Jones Jr.',
    'Harry Giles': 'Harry Giles III',
    'Cam Johnson': 'Cameron Johnson',
    'Nicolas Claxton': 'Nic Claxton',
}
