# Generated by Django 4.2.9 on 2024-08-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='QB',
            field=models.BooleanField(default=False),
        ),
    ]
