# Generated by Django 4.0.4 on 2024-01-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slate',
            name='sport',
            field=models.CharField(choices=[('NBA', 'NBA'), ('MLB', 'MLB'), ('NFL', 'NFL'), ('NHL', 'NHL')], default='NBA', max_length=4),
            preserve_default=False,
        ),
    ]
