# Generated by Django 4.2.9 on 2024-01-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0002_slate_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='positions',
            field=models.ManyToManyField(to='nba.position'),
        ),
    ]
