# Generated by Django 4.2.9 on 2024-01-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0005_remove_player_positions_delete_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='positions',
            field=models.CharField(blank=True, choices=[('F', 'F'), ('C', 'C'), ('G', 'G'), ('PG', 'PG'), ('SG', 'SG'), ('PF', 'PF'), ('SF', 'SF'), ('UTIL', 'UTIL')], max_length=10, null=True),
        ),
    ]
