# Generated by Django 4.2.9 on 2024-01-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0006_alter_player_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('F', 'F'), ('C', 'C'), ('G', 'G'), ('PG', 'PG'), ('SG', 'SG'), ('PF', 'PF'), ('SF', 'SF'), ('UTIL', 'UTIL')], max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='positions',
        ),
        migrations.AddField(
            model_name='player',
            name='positions',
            field=models.ManyToManyField(choices=[('F', 'F'), ('C', 'C'), ('G', 'G'), ('PG', 'PG'), ('SG', 'SG'), ('PF', 'PF'), ('SF', 'SF'), ('UTIL', 'UTIL')], to='nba.position'),
        ),
    ]
