# Generated by Django 4.2.9 on 2024-01-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0007_position_remove_player_positions_player_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='positions',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.AddField(
            model_name='player',
            name='positions',
            field=models.CharField(choices=[('F', 'F'), ('C', 'C'), ('G', 'G'), ('PG', 'PG'), ('SG', 'SG'), ('PF', 'PF'), ('SF', 'SF'), ('UTIL', 'UTIL')], default='PF', max_length=255),
            preserve_default=False,
        ),
    ]
