# Generated by Django 4.2.9 on 2024-01-22 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0009_remove_player_positions_player_isc_player_isf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='isC',
            new_name='C',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='isF',
            new_name='F',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='isG',
            new_name='G',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='isPF',
            new_name='PF',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='isPG',
            new_name='PG',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='isSF',
            new_name='SF',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='isSG',
            new_name='SG',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='isUTIL',
            new_name='UTIL',
        ),
    ]
