# Generated by Django 4.2.9 on 2024-01-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0010_rename_isc_player_c_rename_isf_player_f_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default='C', max_length=5),
            preserve_default=False,
        ),
    ]
