# Generated by Django 4.2.9 on 2024-01-22 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0011_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='opponent',
            field=models.ForeignKey(
                default='1', on_delete=django.db.models.deletion.CASCADE, to='nba.team'),
            preserve_default=False,
        ),
    ]
