# Generated by Django 4.2.9 on 2024-01-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0012_team_opponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='opponent',
            field=models.CharField(max_length=5),
        ),
    ]
