# Generated by Django 4.2.9 on 2024-01-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0013_alter_team_opponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='opponent',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='opponent',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
