# Generated by Django 4.2.9 on 2024-01-26 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nba', '0014_player_opponent_alter_team_opponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock', models.BooleanField(default=False)),
                ('remove', models.BooleanField(default=False)),
                ('ownership', models.DecimalField(decimal_places=2, max_digits=4)),
                ('exposure', models.DecimalField(decimal_places=2, max_digits=4)),
                ('projection', models.DecimalField(decimal_places=2, max_digits=4)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba.player')),
                ('slate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba.slate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
