# Generated by Django 4.2.9 on 2024-02-01 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nba', '0016_rename_player_userplayer_meta_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSlateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_salary', models.IntegerField()),
                ('min_salary', models.IntegerField()),
                ('max_players_per_team', models.IntegerField()),
                ('uniques', models.IntegerField()),
                ('slate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slate_settings_for_user', to='nba.slate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
