# Generated by Django 4.2.9 on 2024-02-01 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nba', '0017_userslatesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOptoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_salary', models.IntegerField()),
                ('min_salary', models.IntegerField()),
                ('max_players_per_team', models.IntegerField()),
                ('uniques', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Slate Setting',
            },
        ),
        migrations.AlterModelOptions(
            name='userplayer',
            options={'verbose_name': 'User Player'},
        ),
        migrations.DeleteModel(
            name='UserSlateSettings',
        ),
    ]
