# Generated by Django 4.2.9 on 2024-02-01 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0018_useroptosettings_alter_userplayer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useroptosettings',
            options={'verbose_name': 'User Opto Setting'},
        ),
    ]
