# Generated by Django 4.2.9 on 2024-02-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0019_alter_useroptosettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroptosettings',
            name='max_players_per_team',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='useroptosettings',
            name='max_salary',
            field=models.IntegerField(default=50000),
        ),
        migrations.AlterField(
            model_name='useroptosettings',
            name='min_salary',
            field=models.IntegerField(default=49000),
        ),
        migrations.AlterField(
            model_name='useroptosettings',
            name='uniques',
            field=models.IntegerField(default=3),
        ),
    ]
