# Generated by Django 4.0.4 on 2024-02-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0020_alter_useroptosettings_max_players_per_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplayer',
            name='exposure',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userplayer',
            name='ownership',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userplayer',
            name='projection',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
