# Generated by Django 4.0.4 on 2024-02-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0023_optimization'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroptosettings',
            name='only_my',
            field=models.BooleanField(default=False),
        ),
    ]
