# Generated by Django 4.2.9 on 2024-02-14 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nba', '0025_remove_useroptosettings_only_my'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimization',
            name='ignore_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='IgnoreOpto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ignore_id', models.CharField(max_length=10)),
                ('slate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba.slate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
