# Generated by Django 4.2.9 on 2024-02-14 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nba', '0026_optimization_ignore_id_ignoreopto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ignoreopto',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
