# Generated by Django 4.2.9 on 2024-03-14 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0027_alter_ignoreopto_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optimization',
            name='ignore_id',
        ),
        migrations.DeleteModel(
            name='IgnoreOpto',
        ),
    ]
