# Generated by Django 4.2.9 on 2026-03-26 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0028_remove_optimization_ignore_id_delete_ignoreopto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_entries', models.IntegerField()),
                ('player_ownership', models.JSONField()),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('slate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contest_results', to='nba.slate')),
            ],
        ),
    ]
