# Generated by Django 4.2.9 on 2024-02-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_confirmation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
