# Generated by Django 4.2.9 on 2024-02-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_confirmation_code_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
