# Generated by Django 4.2.9 on 2024-03-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroptosettings',
            name='hittersVsPitcher',
            field=models.IntegerField(default=0),
        ),
    ]
