# Generated by Django 4.2.9 on 2026-03-24 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0002_useroptosettings_hittersvspitcher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_entries', models.IntegerField()),
                ('player_ownership', models.JSONField()),
                ('stacks', models.JSONField()),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('slate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contest_results', to='mlb.slate')),
            ],
        ),
    ]
